In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fashionmnist/t10k-labels-idx1-ubyte
/kaggle/input/fashionmnist/t10k-images-idx3-ubyte
/kaggle/input/fashionmnist/fashion-mnist_test.csv
/kaggle/input/fashionmnist/fashion-mnist_train.csv
/kaggle/input/fashionmnist/train-labels-idx1-ubyte
/kaggle/input/fashionmnist/train-images-idx3-ubyte


In [2]:
df_train = pd.read_csv("/kaggle/input/fashionmnist/fashion-mnist_train.csv")
df_test = pd.read_csv("/kaggle/input/fashionmnist/fashion-mnist_test.csv")

# General Overview of the Dataset

In [3]:
df_train.shape

(60000, 785)

In [4]:
df_test.shape

(10000, 785)

In [5]:
df_train.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [6]:
df_test.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [7]:
df_train.isnull().sum()

label       0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Length: 785, dtype: int64

In [8]:
df_test.isnull().sum()

label       0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Length: 785, dtype: int64

In [9]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB


In [10]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 59.9 MB


In [11]:
df_train.describe()

label        pixel1        pixel2        pixel3        pixel4  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       4.500000      0.000900      0.006150      0.035333      0.101933   
std        2.872305      0.094689      0.271011      1.222324      2.452871   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      0.000000      0.000000      0.000000   
50%        4.500000      0.000000      0.000000      0.000000      0.000000   
75%        7.000000      0.000000      0.000000      0.000000      0.000000   
max        9.000000     16.000000     36.000000    226.000000    164.000000   

             pixel5        pixel6        pixel7        pixel8        pixel9  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       0.247967      0.411467      0.805767      2.198283      5.682000   
std        4.306912      5.836188      8.215169     14.093378     23.819481   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      227.000000    230.000000    224.000000    255.000000    254.000000   

       ...      pixel775      pixel776      pixel777      pixel778  \
count  ...  60000.000000  60000.000000  60000.000000  60000.000000   
mean   ...     34.625400     23.300683     16.588267     17.869433   
std    ...     57.545242     48.854427     41.979611     43.966032   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...     58.000000      9.000000      0.000000      0.000000   
max    ...    255.000000    255.000000    255.000000    255.000000   

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean      22.814817     17.911483      8.520633      2.753300      0.855517   
std       51.830477     45.149388     29.614859     17.397652      9.356960   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      255.000000    255.000000    255.000000    255.000000    255.000000   

          pixel784  
count  60000.00000  
mean       0.07025  
std        2.12587  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max      170.00000  

[8 rows x 785 columns]

In [12]:
df_test.describe()

label        pixel1        pixel2        pixel3        pixel4  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       4.500000      0.000400      0.010300      0.052100      0.077000   
std        2.872425      0.024493      0.525187      2.494315      2.208882   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      0.000000      0.000000      0.000000   
50%        4.500000      0.000000      0.000000      0.000000      0.000000   
75%        7.000000      0.000000      0.000000      0.000000      0.000000   
max        9.000000      2.000000     45.000000    218.000000    185.000000   

             pixel5        pixel6        pixel7        pixel8        pixel9  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       0.208600      0.349200      0.826700      2.321200      5.457800   
std        4.669183      5.657849      8.591731     15.031508     23.359019   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      227.000000    223.000000    247.000000    218.000000    244.000000   

       ...      pixel775      pixel776      pixel777      pixel778  \
count  ...  10000.000000  10000.000000  10000.000000  10000.000000   
mean   ...     34.320800     23.071900     16.432000     17.870600   
std    ...     57.888679     49.049749     42.159665     44.140552   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...     55.000000      6.000000      0.000000      0.000000   
max    ...    254.000000    252.000000    255.000000    255.000000   

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      22.860000     17.790200      8.353500      2.541600      0.629500   
std       51.706601     45.128107     28.765769     16.417363      7.462533   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        1.000000      0.000000      0.000000      0.000000      0.000000   
max      255.000000    255.000000    240.000000    225.000000    205.000000   

          pixel784  
count  10000.00000  
mean       0.06560  
std        1.93403  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max      107.00000  

[8 rows x 785 columns]

### Loading Dataset

In [13]:
df_train_y = df_train.label
y_test = df_test.label

In [14]:
df_train_x = df_train.drop("label", axis=1)/256
x_test = df_test.drop("label", axis=1)/256


### Splitting and Training

In [15]:
np.random.seed(0)

valid2_idx = np.random.choice(60000,10000,replace=False)
valid1_idx = np.random.choice(list(set(range(60000)) - set(valid2_idx)), 10000, replace=False)
train_idx = list(set(range(60000)) - set(valid1_idx) - set(valid2_idx))

x_train = df_train_x.iloc[train_idx,:]
y_train = df_train_y.iloc[train_idx]

x_valid1 = df_train_x.iloc[valid1_idx,:]
y_valid1 = df_train_y.iloc[valid1_idx]

x_valid2 = df_train_x.iloc[valid2_idx,:]
y_valid2 = df_train_y.iloc[valid2_idx]

# RandomForestClassifier

### Importing RandomForestClassifier

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

### Fitting

In [17]:
RF_model = RandomForestClassifier(n_estimators=1000, max_depth=50, random_state=42)
RF_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=50, n_estimators=1000, random_state=42)

### Training Accuracy

In [18]:
confusion_matrix(RF_model.predict(x_train), y_train)

array([[3994,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 3990,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4056,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 3929,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 4016,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 3932,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4005,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 4103,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 3946,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4029]])

In [19]:
RF_model_train_acc = (RF_model.predict(x_train) == y_train).mean()
print("Training Accuracy =", RF_model_train_acc)

Training Accuracy = 1.0


### Validation Accuracy

In [20]:
confusion_matrix(RF_model.predict(x_valid1),y_valid1)

array([[ 886,    2,    6,   22,    4,    0,  163,    0,    2,    0],
       [   0,  996,    0,    0,    2,    0,    1,    0,    1,    0],
       [   5,    2,  777,    5,   83,    0,  117,    0,    1,    0],
       [  38,   17,   12,  942,   44,    1,   26,    0,    3,    0],
       [   2,    0,  105,   25,  815,    0,   87,    0,    6,    0],
       [   0,    0,    0,    0,    1, 1011,    0,   17,    1,   11],
       [  79,    9,   40,   17,   40,    0,  573,    0,   10,    0],
       [   0,    0,    0,    0,    0,   33,    0,  889,    2,   32],
       [   5,    0,    5,    1,    6,    2,   20,    1, 1008,    3],
       [   0,    0,    0,    0,    0,   13,    0,   41,    0,  932]])

In [21]:
RF_model_valid1_acc = (RF_model.predict(x_valid1) == y_valid1).mean()
print("Validation Accuracy =", RF_model_valid1_acc)

Validation Accuracy = 0.8829


In [22]:
print("Training Accuracy =", RF_model_train_acc)
print("Validation Accuracy =", RF_model_valid1_acc)

Training Accuracy = 1.0
Validation Accuracy = 0.8829


# Logistic Regression

### Importing LogisticRegression

In [23]:
from sklearn.linear_model import LogisticRegression

### Fitting

In [24]:
Log_model = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10, random_state=42)
Log_model.fit(x_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=10, multi_class='multinomial', random_state=42)

### Training Accuracy

In [25]:
confusion_matrix(Log_model.predict(x_train), y_train)

array([[3363,   13,   75,  125,    8,    2,  492,    0,   15,    0],
       [  11, 3849,    7,   38,    7,    0,    8,    0,    4,    1],
       [  66,   15, 3149,   41,  373,    0,  402,    1,   26,    0],
       [ 157,   87,   51, 3484,  141,    1,  135,    0,   35,    1],
       [  18,   13,  397,  108, 3188,    0,  351,    0,   12,    0],
       [   6,    0,    2,    0,    0, 3716,    0,  121,   20,   54],
       [ 335,   10,  353,  118,  290,    1, 2575,    0,   65,    0],
       [   0,    1,    0,    2,    0,  145,    0, 3865,   16,  120],
       [  38,    2,   22,   13,    9,   16,   41,    8, 3753,    2],
       [   0,    0,    0,    0,    0,   51,    1,  108,    0, 3851]])

In [26]:
Log_model_train_acc = (Log_model.predict(x_train) == y_train).mean()
print("Training Accuracy =", Log_model_train_acc)

Training Accuracy = 0.869825


### Validation Accuracy

In [27]:
confusion_matrix(Log_model.predict(x_valid1),y_valid1)

array([[833,   4,  15,  43,   2,   0, 133,   0,   4,   0],
       [  3, 987,   2,  10,   3,   0,   3,   0,   1,   0],
       [ 17,   5, 698,   8,  92,   0, 127,   0,  10,   0],
       [ 51,  18,  14, 886,  53,   0,  27,   1,   9,   0],
       [  0,   2, 107,  30, 747,   0,  97,   0,   3,   0],
       [  0,   0,   1,   0,   1, 969,   0,  25,   4,  17],
       [101,  10, 102,  31,  86,   0, 585,   0,  29,   0],
       [  0,   0,   0,   0,   0,  51,   0, 888,   5,  35],
       [ 10,   0,   6,   4,  11,  11,  15,   2, 968,   1],
       [  0,   0,   0,   0,   0,  29,   0,  32,   1, 925]])

In [28]:
Log_model_valid1_acc = (Log_model.predict(x_valid1) == y_valid1).mean()
print("Validation Accuracy =", Log_model_valid1_acc)

Validation Accuracy = 0.8486


In [29]:
print("Training Accuracy =", Log_model_train_acc)
print("Validation Accuracy =", Log_model_valid1_acc)

Training Accuracy = 0.869825
Validation Accuracy = 0.8486


# XGBClassifier

### Importing XGBoostClassifier

In [30]:
from xgboost import XGBClassifier

### Fitting

In [31]:
xgb_model = XGBClassifier(n_estimators=20, max_depth=10, random_state=42)
xgb_model.fit(x_train, y_train)

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:59:47] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=10,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=20, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=42, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

### Training Accuracy

In [32]:
confusion_matrix(xgb_model.predict(x_train), y_train)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


array([[3988,    0,    0,    3,    0,    0,    1,    0,    0,    0],
       [   0, 3990,    0,    0,    0,    0,    0,    0,    0,    0],
       [   2,    0, 4034,    0,   12,    0,    7,    0,    2,    0],
       [   2,    0,    3, 3919,    4,    0,    1,    0,    1,    0],
       [   2,    0,   16,    7, 3992,    0,    1,    0,    0,    0],
       [   0,    0,    0,    0,    0, 3932,    0,    0,    0,    0],
       [   0,    0,    3,    0,    8,    0, 3995,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 4103,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 3943,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4029]])

In [33]:
xgb_model_train_acc = (xgb_model.predict(x_train) == y_train).mean()
print("Training Accuracy =", xgb_model_train_acc)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


Training Accuracy = 0.998125


### Validation Accuracy

In [34]:
confusion_matrix(xgb_model.predict(x_valid1),y_valid1)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


array([[ 879,    3,    9,   27,    5,    0,  144,    0,    2,    0],
       [   2,  995,    0,    0,    2,    0,    2,    0,    1,    0],
       [   5,    1,  756,    3,   74,    0,  105,    0,    1,    0],
       [  30,   20,    6,  933,   47,    1,   23,    0,    4,    0],
       [   1,    0,  105,   23,  808,    0,   80,    0,    6,    0],
       [   0,    0,    1,    1,    0, 1010,    0,   18,    1,   10],
       [  93,    7,   64,   24,   55,    0,  617,    0,   15,    0],
       [   0,    0,    0,    0,    0,   29,    0,  900,    2,   30],
       [   5,    0,    4,    1,    4,    5,   16,    2, 1002,    4],
       [   0,    0,    0,    0,    0,   15,    0,   28,    0,  934]])

In [35]:
xgb_model_valid1_acc = (xgb_model.predict(x_valid1) == y_valid1).mean()
print("Validation Accuracy =", xgb_model_valid1_acc)

/opt/conda/lib/python3.7/site-packages/xgboost/data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


Validation Accuracy = 0.8834


In [36]:
print("Training Accuracy =", xgb_model_train_acc)
print("Validation Accuracy =", xgb_model_valid1_acc)

Training Accuracy = 0.998125
Validation Accuracy = 0.8834


# Gradient Boosting

### Importing GradientBoostingClassifier

In [37]:
from sklearn.ensemble import GradientBoostingClassifier

### Fitting

In [38]:
GB_model = GradientBoostingClassifier(n_estimators=10,learning_rate=0.5)
GB_model.fit(x_train, y_train)

GradientBoostingClassifier(learning_rate=0.5, n_estimators=10)

### Training Accuracy

In [39]:
confusion_matrix(GB_model.predict(x_train), y_train)

array([[3276,   20,   54,  113,   16,    3,  518,    0,   13,    2],
       [   8, 3866,    5,   41,    6,    1,   14,    0,    6,    2],
       [  54,   11, 3126,   45,  398,    0,  413,    0,   23,    4],
       [ 159,   74,   41, 3485,  188,    1,  129,    0,   32,    4],
       [  23,    9,  470,  118, 3092,    4,  343,    1,   29,    1],
       [   1,    2,    0,    6,    0, 3693,    3,   78,   22,   45],
       [ 427,    7,  338,  115,  301,    0, 2523,    0,   58,    1],
       [   0,    0,    0,    0,    0,  152,    1, 3839,   21,  148],
       [  46,    1,   22,    6,   15,   19,   60,    6, 3739,    4],
       [   0,    0,    0,    0,    0,   59,    1,  179,    3, 3818]])

In [40]:
GB_model_train_acc = (GB_model.predict(x_train) == y_train).mean()
print("Training Accuracy =", GB_model_train_acc)

Training Accuracy = 0.861425


### Validation Accuracy

In [41]:
confusion_matrix(GB_model.predict(x_valid1),y_valid1)

array([[821,   7,  18,  31,   3,   0, 148,   0,   2,   0],
       [  5, 983,   2,  16,   5,   2,   5,   0,   5,   0],
       [ 12,   3, 680,   8, 121,   1, 127,   0,   6,   0],
       [ 48,  26,  14, 883,  62,   0,  27,   1,  11,   2],
       [  4,   3, 119,  31, 719,   0, 109,   0,  12,   1],
       [  0,   0,   2,   2,   2, 968,   2,  21,   6,  16],
       [116,   3, 100,  37,  77,   0, 547,   0,  23,   1],
       [  0,   0,   0,   0,   0,  45,   0, 864,   8,  52],
       [  9,   1,   9,   3,   6,  11,  22,   4, 961,   5],
       [  0,   0,   1,   1,   0,  33,   0,  58,   0, 901]])

In [42]:
GB_model_valid1_acc = (GB_model.predict(x_valid1) == y_valid1).mean()
print("Validation Accuracy =", GB_model_valid1_acc)

Validation Accuracy = 0.8327


In [43]:
print("Training Accuracy =", GB_model_train_acc)
print("Validation Accuracy =", GB_model_valid1_acc)

Training Accuracy = 0.861425
Validation Accuracy = 0.8327


# Support Vector Machine

### Importing SVC

In [44]:
from sklearn.svm import SVC

### Fitting

In [45]:
SVM_model = SVC(C=100)
SVM_model.fit(x_train, y_train)

SVC(C=100)

### Training Accuracy

In [46]:
confusion_matrix(SVM_model.predict(x_train), y_train)

array([[3994,    0,    0,    0,    0,    0,    2,    0,    0,    0],
       [   0, 3990,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4055,    0,    0,    0,    1,    0,    0,    0],
       [   0,    0,    0, 3929,    0,    0,    0,    0,    0,    0],
       [   0,    0,    1,    0, 4016,    0,    1,    0,    0,    0],
       [   0,    0,    0,    0,    0, 3932,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4001,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 4103,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 3946,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4029]])

In [47]:
SVM_model_train_acc = (SVM_model.predict(x_train) == y_train).mean()
print("Training Accuracy =", SVM_model_train_acc)

Training Accuracy = 0.999875


### Validation Accuracy

In [48]:
confusion_matrix(SVM_model.predict(x_valid1),y_valid1)

array([[ 864,    4,   26,   41,    7,    0,  101,    0,    6,    0],
       [   3, 1009,    1,    7,    2,    0,    2,    0,    1,    0],
       [   9,    0,  782,   14,   96,    0,   86,    0,    1,    0],
       [  26,    9,    7,  907,   33,    0,   23,    0,    7,    0],
       [   1,    0,   79,   29,  801,    0,   57,    0,    4,    0],
       [   0,    0,    0,    0,    0, 1032,    0,   11,    3,    7],
       [ 109,    4,   50,   11,   54,    0,  709,    0,    5,    0],
       [   0,    0,    0,    0,    0,   17,    0,  901,    3,   28],
       [   3,    0,    0,    3,    2,    3,    9,    2, 1004,    1],
       [   0,    0,    0,    0,    0,    8,    0,   34,    0,  942]])

In [49]:
SVM_model_valid1_acc = (SVM_model.predict(x_valid1) == y_valid1).mean()
print("Validation Accuracy =", SVM_model_valid1_acc)

Validation Accuracy = 0.8951


In [50]:
print("Training Accuracy =", SVM_model_train_acc)
print("Validation Accuracy =", SVM_model_valid1_acc)

Training Accuracy = 0.999875
Validation Accuracy = 0.8951
